{"name": "Тест Обновления информации неавторизованным пользователем невозможно", "status": "passed", "description": "Тест проверяет ошибку при попытке обновления данных неавторизованным пользователем", "start": 1718120241834, "stop": 1718120242044, "uuid": "5e7cf432-cbe4-441b-8e1a-bed14fe43491", "historyId": "c0b1f4c237ec72a59f0c6e2f01531c1d", "testCaseId": "c0b1f4c237ec72a59f0c6e2f01531c1d", "fullName": "tests.test_change_user_data.TestChangeUserData#test_update_userdata_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_user_data"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "WIN-FL5IV5LS9IV"}, {"name": "thread", "value": "29088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_user_data"}]}